-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.addon_catalog (
  addon_code text NOT NULL,
  name text NOT NULL,
  unit text,
  price_cents integer NOT NULL,
  stripe_price_id text NOT NULL,
  billing_mode text NOT NULL,
  CONSTRAINT addon_catalog_pkey PRIMARY KEY (addon_code)
);
CREATE TABLE public.agent_phone_numbers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  phone_number text NOT NULL UNIQUE,
  twilio_sid text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT agent_phone_numbers_pkey PRIMARY KEY (id),
  CONSTRAINT agent_phone_numbers_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.call_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  twilio_call_sid character varying NOT NULL UNIQUE,
  call_direction character varying NOT NULL CHECK (call_direction::text = ANY (ARRAY['inbound'::character varying, 'outbound'::character varying]::text[])),
  from_number character varying NOT NULL,
  to_number character varying NOT NULL,
  agent_id uuid,
  organization_id uuid,
  lead_id uuid,
  call_status character varying NOT NULL DEFAULT 'initiated'::character varying CHECK (call_status::text = ANY (ARRAY['initiated'::character varying, 'ringing'::character varying, 'answered'::character varying, 'completed'::character varying, 'busy'::character varying, 'no-answer'::character varying, 'failed'::character varying, 'canceled'::character varying]::text[])),
  call_duration integer DEFAULT 0,
  call_start_time timestamp with time zone,
  call_end_time timestamp with time zone,
  call_quality_score numeric,
  recording_url text,
  recording_duration integer,
  twilio_price numeric,
  twilio_price_unit character varying DEFAULT 'USD'::character varying,
  call_notes text,
  call_tags ARRAY,
  call_outcome character varying CHECK (call_outcome::text = ANY (ARRAY['successful'::character varying, 'no-answer'::character varying, 'busy'::character varying, 'failed'::character varying, 'voicemail'::character varying, 'callback-requested'::character varying, 'not-interested'::character varying]::text[])),
  follow_up_required boolean DEFAULT false,
  follow_up_date date,
  follow_up_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT call_history_pkey PRIMARY KEY (id),
  CONSTRAINT call_history_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT call_history_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id),
  CONSTRAINT call_history_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.communications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['email'::character varying, 'text'::character varying, 'call'::character varying]::text[])),
  direction character varying NOT NULL CHECK (direction::text = ANY (ARRAY['inbound'::character varying, 'outbound'::character varying]::text[])),
  subject character varying,
  content text NOT NULL,
  timestamp timestamp with time zone DEFAULT now(),
  duration integer,
  status character varying DEFAULT 'sent'::character varying CHECK (status::text = ANY (ARRAY['sent'::character varying, 'delivered'::character varying, 'read'::character varying, 'failed'::character varying]::text[])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  user_id uuid,
  CONSTRAINT communications_pkey PRIMARY KEY (id),
  CONSTRAINT communications_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT communications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT communications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT communications_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id)
);
CREATE TABLE public.invoice_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  stripe_invoice_id text,
  period_start timestamp with time zone,
  period_end timestamp with time zone,
  items jsonb,
  subtotal_cents integer,
  tax_cents integer,
  total_cents integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invoice_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_snapshots_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  company character varying,
  stage character varying NOT NULL DEFAULT 'new'::character varying CHECK (stage::text = ANY (ARRAY['new'::character varying, 'contacted'::character varying, 'qualified'::character varying, 'proposal'::character varying, 'closed-won'::character varying, 'closed-lost'::character varying]::text[])),
  value numeric DEFAULT 0,
  title character varying,
  description text,
  category character varying,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'in_progress'::character varying, 'closed'::character varying]::text[])),
  priority character varying DEFAULT 'low'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  tags ARRAY DEFAULT '{}'::text[],
  last_contact date,
  notes text,
  organization_id uuid,
  assigned_to uuid,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT leads_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT leads_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid,
  title text,
  message text,
  type text NOT NULL DEFAULT 'general'::text,
  priority text NOT NULL DEFAULT 'medium'::text,
  action_url text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  read_at timestamp with time zone,
  reminder_id uuid,
  shown boolean,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_reminder_id_fkey FOREIGN KEY (reminder_id) REFERENCES public.task_reminders(id)
);
CREATE TABLE public.org_suspensions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  kind text NOT NULL,
  reason text,
  requested_by uuid,
  effective_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT org_suspensions_pkey PRIMARY KEY (id),
  CONSTRAINT org_suspensions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organization_invites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL,
  role character varying NOT NULL,
  organization_id uuid NOT NULL,
  invited_by uuid NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'expired'::character varying, 'cancelled'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  CONSTRAINT organization_invites_pkey PRIMARY KEY (id),
  CONSTRAINT organization_invites_invited_by_fkey1 FOREIGN KEY (invited_by) REFERENCES public.profiles(id),
  CONSTRAINT organization_invites_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  owner_id uuid NOT NULL,
  max_seats integer DEFAULT 10,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'pending'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  website text,
  industry text,
  ein text,
  address_street text,
  address_city text,
  address_state text,
  address_zip text,
  address_country text,
  stripe_customer_id text UNIQUE,
  stripe_subscription_id text,
  stripe_status text,
  stripe_collection_method text,
  stripe_latest_invoice_id text,
  stripe_latest_invoice_status text,
  stripe_subscription_status_reason text,
  stripe_subscription_metadata jsonb,
  stripe_pause_collection jsonb,
  org_status text DEFAULT 'active'::text,
  plan_code text DEFAULT 'starter'::text,
  plan_price_cents integer DEFAULT 12900,
  included_seats integer DEFAULT 1,
  included_minutes integer DEFAULT 500,
  included_sms integer DEFAULT 200,
  included_emails integer DEFAULT 1000,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  trial_end timestamp with time zone,
  trial_ending_soon boolean DEFAULT false,
  cancel_at_period_end boolean,
  payment_action_required boolean DEFAULT false,
  payment_retry_count integer DEFAULT 0,
  next_payment_retry_at timestamp with time zone,
  last_payment_failed_at timestamp with time zone,
  payment_failure_reason text,
  dunning_enabled boolean DEFAULT false,
  twilio_subaccount_sid text,
  vapi_assistant_id text,
  tz text DEFAULT 'America/New_York'::text,
  trusthub_profile_sid text,
  a2p_campaign_id text,
  a2p_campaign_status text,
  a2p_campaign_reject_reason text,
  tollfree_verification_status text,
  tollfree_reject_reason text,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.plan_catalog (
  plan_code text NOT NULL,
  name text NOT NULL,
  base_price_cents integer NOT NULL,
  included_seats integer NOT NULL,
  included_minutes integer NOT NULL,
  included_sms integer NOT NULL,
  included_emails integer NOT NULL,
  stripe_price_id text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  active boolean DEFAULT true,
  env text DEFAULT 'test'::text CHECK (env = ANY (ARRAY['test'::text, 'live'::text])),
  CONSTRAINT plan_catalog_pkey PRIMARY KEY (plan_code)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  first_name text,
  last_name text,
  completed_onboarding boolean,
  avatar text,
  title text DEFAULT ''::text,
  bio text DEFAULT ''::text,
  phone text DEFAULT ''::text,
  location text DEFAULT ''::text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.seat_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  seat_id uuid,
  action text NOT NULL,
  reason text,
  delta integer NOT NULL,
  stripe_item_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT seat_events_pkey PRIMARY KEY (id),
  CONSTRAINT seat_events_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT seat_events_seat_id_fkey FOREIGN KEY (seat_id) REFERENCES public.seats(id)
);
CREATE TABLE public.seats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid,
  phone_sid text,
  phone_e164 text,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT seats_pkey PRIMARY KEY (id),
  CONSTRAINT seats_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.sms_brand_profile (
  org_id uuid NOT NULL,
  legal_name text NOT NULL,
  business_type text NOT NULL,
  ein text NOT NULL,
  website text NOT NULL,
  industry text NOT NULL,
  addr_street text NOT NULL,
  addr_city text NOT NULL,
  addr_state text NOT NULL,
  addr_zip text NOT NULL,
  addr_country text NOT NULL,
  contact_name text NOT NULL,
  contact_email text NOT NULL,
  contact_phone text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sms_brand_profile_pkey PRIMARY KEY (org_id),
  CONSTRAINT sms_brand_profile_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.sms_campaign_profile (
  org_id uuid NOT NULL,
  use_case_description text NOT NULL,
  opt_in_method text NOT NULL,
  sample_msg_1 text NOT NULL,
  sample_msg_2 text NOT NULL,
  opt_out_text text NOT NULL,
  help_text text NOT NULL,
  terms_url text NOT NULL,
  privacy_url text NOT NULL,
  est_monthly_messages integer NOT NULL,
  countries ARRAY NOT NULL DEFAULT '{US}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sms_campaign_profile_pkey PRIMARY KEY (org_id),
  CONSTRAINT sms_campaign_profile_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.sms_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  phone_number text NOT NULL,
  to_number text NOT NULL,
  from_number text NOT NULL,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['inbound'::text, 'outbound'::text])),
  body text,
  status text,
  twilio_sid text UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  lead_id uuid,
  archived boolean,
  CONSTRAINT sms_messages_pkey PRIMARY KEY (id),
  CONSTRAINT sms_messages_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT sms_messages_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.subscription_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  stripe_subscription_id text,
  event text NOT NULL,
  from_plan text,
  to_plan text,
  proration_cents integer DEFAULT 0,
  raw jsonb,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscription_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_ledger_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.task_reminders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  task_id uuid NOT NULL,
  reminder_time timestamp with time zone NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (TRIM(BOTH FROM lower(status::text)) = ANY (ARRAY['pending'::text, 'delivered'::text, 'canceled'::text])),
  notification_type character varying DEFAULT 'browser'::character varying CHECK (notification_type::text = ANY (ARRAY['browser'::character varying, 'email'::character varying, 'both'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT task_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT task_reminders_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying NOT NULL,
  description text,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'completed'::character varying]::text[])),
  priority character varying NOT NULL DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['urgent'::character varying, 'high'::character varying, 'medium'::character varying, 'low'::character varying]::text[])),
  type character varying NOT NULL DEFAULT 'general'::character varying CHECK (type::text = ANY (ARRAY['follow_up'::character varying, 'call'::character varying, 'email'::character varying, 'meeting'::character varying, 'proposal'::character varying, 'general'::character varying]::text[])),
  due_date timestamp with time zone NOT NULL,
  reminder_enabled boolean DEFAULT false,
  lead_id uuid,
  lead_name character varying,
  organization_id uuid NOT NULL,
  owner_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  reminder_time timestamp with time zone,
  due_timezone text NOT NULL DEFAULT 'UTC'::text,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id),
  CONSTRAINT tasks_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT tasks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.team_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'member'::text CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_members_pkey PRIMARY KEY (id),
  CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT team_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.usage_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  seat_id uuid,
  category text NOT NULL,
  unit text NOT NULL,
  qty numeric NOT NULL,
  provider text,
  raw_cost_cents integer,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT usage_events_pkey PRIMARY KEY (id),
  CONSTRAINT usage_events_seat_id_fkey FOREIGN KEY (seat_id) REFERENCES public.seats(id),
  CONSTRAINT usage_events_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.usage_period_rollups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  minutes_total numeric NOT NULL DEFAULT 0,
  sms_total numeric NOT NULL DEFAULT 0,
  emails_total numeric NOT NULL DEFAULT 0,
  minutes_overage numeric NOT NULL DEFAULT 0,
  sms_overage numeric NOT NULL DEFAULT 0,
  emails_overage numeric NOT NULL DEFAULT 0,
  stripe_usage_push_status text DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT usage_period_rollups_pkey PRIMARY KEY (id),
  CONSTRAINT usage_period_rollups_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_notification_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  browser_notifications boolean DEFAULT true,
  email_notifications boolean DEFAULT true,
  push_notifications boolean DEFAULT true,
  reminder_advance_minutes integer DEFAULT 15,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_notification_settings_pkey PRIMARY KEY (id),
  CONSTRAINT user_notification_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_notification_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  organization_id uuid,
  role character varying DEFAULT 'member'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_organizations_pkey PRIMARY KEY (id),
  CONSTRAINT user_organizations_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_organizations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_organizations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_phone_numbers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  phone_number text UNIQUE,
  area_code character varying,
  provider text DEFAULT 'twilio'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  twilio_number_sid text,
  messaging_service_sid text,
  e164 text CHECK (e164 IS NULL OR e164 ~ '^\+[1-9][0-9]{6,14}$'::text),
  country text,
  capabilities ARRAY,
  status text DEFAULT 'active'::text,
  purchased_at timestamp with time zone DEFAULT now(),
  voice_webhook_url text,
  sms_webhook_url text,
  assigned_at timestamp with time zone,
  released_at timestamp with time zone,
  CONSTRAINT user_phone_numbers_pkey PRIMARY KEY (id),
  CONSTRAINT user_phone_numbers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_phone_numbers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.stripe_subscription_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  stripe_subscription_id text NOT NULL,
  stripe_customer_id text,
  event_type text NOT NULL,
  status text,
  collection_method text,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  trial_end timestamp with time zone,
  cancel_at timestamp with time zone,
  cancel_at_period_end boolean,
  default_payment_method_id text,
  raw_payload jsonb NOT NULL,
  received_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stripe_subscription_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_subscription_snapshots_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.stripe_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  stripe_invoice_id text NOT NULL,
  stripe_customer_id text,
  status text,
  hosted_invoice_url text,
  invoice_pdf text,
  currency text,
  subtotal integer,
  tax integer,
  total integer,
  amount_due integer,
  amount_paid integer,
  amount_remaining integer,
  period_start timestamp with time zone,
  period_end timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  finalized_at timestamp with time zone,
  paid_at timestamp with time zone,
  raw_payload jsonb NOT NULL,
  CONSTRAINT stripe_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_invoices_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.payment_failure_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  stripe_invoice_id text,
  error_message text,
  retry_count integer,
  occurred_at timestamp with time zone DEFAULT now(),
  raw_payload jsonb,
  CONSTRAINT payment_failure_events_pkey PRIMARY KEY (id),
  CONSTRAINT payment_failure_events_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);