/**
 * S1-7: Toxic Link Detection + Disavow
 * Scores referring domains, flags toxic links, generates disavow file.
 * See docs/product-gaps-master.md V2.3
 */

import { getReferringDomains } from '../utils/dataforseoBacklinks.js';
import { supabase } from '../utils/supabaseClient.js';

/** Toxic threshold: spam score >= this OR rank < this (on 0-100 scale) */
const SPAM_SCORE_TOXIC = 30;
const RANK_TOXIC = 15; // rank < 15 = very low authority

export interface ToxicDomain {
	domain: string;
	reason: string;
	rank: number;
	spam_score?: number;
	backlinks: number;
}

export interface ToxicLinksAuditResult {
	evaluated_at: string;
	total_domains: number;
	toxic_count: number;
	toxic_domains: ToxicDomain[];
	disavow_content: string;
	summary: string;
}

function isToxic(domain: {
	rank: number;
	backlinks_spam_score?: number;
}): { toxic: boolean; reason: string } {
	const spam = domain.backlinks_spam_score ?? 0;
	const rank = domain.rank ?? 0;

	if (spam >= SPAM_SCORE_TOXIC) {
		return {
			toxic: true,
			reason: `High spam score (${spam}/100). Often indicates link farms, PBNs, or low-quality directories.`,
		};
	}
	if (rank > 0 && rank < RANK_TOXIC) {
		return {
			toxic: true,
			reason: `Very low domain authority (rank ${rank}/100). May be a low-quality or spam site.`,
		};
	}
	// Combined: moderate spam + low rank
	if (spam >= 15 && rank < 25) {
		return {
			toxic: true,
			reason: `Moderate spam score (${spam}) combined with low authority (rank ${rank}).`,
		};
	}
	return { toxic: false, reason: '' };
}

/**
 * Generate disavow file content in Google's format.
 * Format: domain:example.com (one per line)
 */
function generateDisavowFile(domains: string[]): string {
	const header = `# Disavow file generated by Sharkly
# Submit at: https://search.google.com/search-console/disavow-links
# Format: domain:example.com (disavow entire domain)
# See: https://support.google.com/webmasters/answer/96569

`;
	const lines = domains.map((d) => `domain:${d}`).join('\n');
	return header + lines;
}

export async function runToxicLinksAudit(siteId: string): Promise<ToxicLinksAuditResult> {
	const evaluated_at = new Date().toISOString();

	const { data: site, error: siteErr } = await supabase
		.from('sites')
		.select('id, url')
		.eq('id', siteId)
		.single();

	if (siteErr || !site) {
		throw new Error('Site not found');
	}

	const siteUrl = (site.url || '').trim();
	if (!siteUrl) {
		throw new Error('Site URL is required for backlink audit');
	}

	const { domains, total_count, configured, error } = await getReferringDomains(siteUrl, {
		limit: 500,
		rankScale: 'one_hundred',
	});

	if (!configured) {
		throw new Error('DataForSEO is not configured. Add DATAFORSEO_LOGIN and DATAFORSEO_PASSWORD to enable toxic link detection.');
	}
	if (error) {
		throw new Error(`Backlink fetch failed: ${error}`);
	}

	const toxic_domains: ToxicDomain[] = [];

	for (const d of domains) {
		const { toxic, reason } = isToxic({
			rank: d.rank,
			backlinks_spam_score: d.backlinks_spam_score,
		});
		if (toxic) {
			toxic_domains.push({
				domain: d.domain,
				reason,
				rank: d.rank,
				spam_score: d.backlinks_spam_score,
				backlinks: d.backlinks,
			});
		}
	}

	const disavow_content = generateDisavowFile(toxic_domains.map((t) => t.domain));

	const summary =
		toxic_domains.length === 0
			? 'No toxic links detected. Your backlink profile looks clean.'
			: `These ${toxic_domains.length} link${toxic_domains.length > 1 ? 's' : ''} ${toxic_domains.length > 1 ? 'are' : 'is'} from low-quality sites and may be hurting your authority score. We've prepared a disavow file — submit it to Google Search Console.`;

	const result: ToxicLinksAuditResult = {
		evaluated_at,
		total_domains: total_count,
		toxic_count: toxic_domains.length,
		toxic_domains,
		disavow_content,
		summary,
	};

	// Persist to sites
	await supabase
		.from('sites')
		.update({
			toxic_links_audit: result as unknown as object,
			updated_at: evaluated_at,
		})
		.eq('id', siteId);

	// S1-10: Store referring domains in site_backlink_history for brand search ratio
	try {
		await supabase.from('site_backlink_history').insert({
			site_id: siteId,
			recorded_at: evaluated_at,
			referring_domains: total_count,
		});
	} catch (blErr) {
		console.warn('[ToxicLinks] Failed to store backlink history:', blErr);
		// non-fatal
	}

	return result;
}
