export const mockUser = {
	id: '1',
	full_name: 'Alex Rivera',
	plan: 'growth' as const,
	credits_remaining: 387,
	credits_monthly: 600,
};

export const mockProject = {
	id: '1',
	name: 'Universal Investigations Agency',
	url: 'universalinvestigationsagency.com',
	platform: 'WordPress',
	niche: 'Private Investigation Services',
	customer_description:
		'businesses and individuals in Florida who need licensed investigators',
	da: 28,
};

export const mockTopics = [
	{
		id: '1',
		clusterId: '1' as string | null,
		title: 'Cyber Crime Investigation',
		volume: 4200,
		kd: 34,
		cpc: 12.4,
		funnel: 'bofu' as const,
		authorityFit: 'achievable' as const,
		status: 'active' as const,
		priority: 1,
		reasoning:
			'3 of your top competitors rank here and you have a direct service match. KD 34 is within your current authority range.',
	},
	{
		id: '2',
		title: 'Infidelity Investigation',
		volume: 8100,
		kd: 28,
		cpc: 18.2,
		funnel: 'bofu' as const,
		authorityFit: 'achievable' as const,
		status: 'queued' as const,
		priority: 2,
		reasoning:
			'High CPC signals strong buyer intent. Lower KD than expected for the volume.',
	},
	{
		id: '3',
		title: 'Missing Persons Investigation',
		volume: 1900,
		kd: 15,
		cpc: 8.1,
		funnel: 'mofu' as const,
		authorityFit: 'achievable' as const,
		status: 'queued' as const,
		priority: 3,
		reasoning:
			'Low competition and strong local intent. Quick win that builds authority.',
	},
	{
		id: '4',
		title: 'Background Check Services',
		volume: 22000,
		kd: 55,
		cpc: 9.8,
		funnel: 'mofu' as const,
		authorityFit: 'buildToward' as const,
		status: 'locked' as const,
		priority: 4,
		reasoning:
			'Broad topic needs sub-clustering. Unlock after 3-4 clusters are complete.',
	},
	{
		id: '5',
		title: 'Fraud Investigation Services',
		volume: 51800,
		kd: 61,
		cpc: 22.0,
		funnel: 'bofu' as const,
		authorityFit: 'locked' as const,
		status: 'locked' as const,
		priority: 5,
		reasoning:
			'High volume but KD 61 requires significantly more domain authority.',
	},
];

export const mockCluster = {
	id: '1',
	topicId: '1',
	title: 'Cyber Crime Investigation',
	targetKeyword: 'cyber crime investigation',
	estimatedTraffic: 4200,
	completion: 6,
	total: 10,
	croScore: 68,
	authorityFit: 'achievable' as const,
	funnelBalance: { tofu: 7, mofu: 2, bofu: 1 },
	aiInsight:
		'Publishing the 3 drafted articles and adding internal links this week could move your focus page from position 14 into the top 10 within 30 days.',
};

export const mockPages = [
	{
		id: '1',
		clusterId: '1',
		title: 'Cyber Crime Investigation Services',
		type: 'money' as const,
		keyword: 'cyber crime investigation',
		volume: 4200,
		kd: 34,
		funnel: 'bofu' as const,
		status: 'published' as const,
		seoScore: 84,
		croScore: 68,
		wordCount: 1240,
		targetWordCount: 1400,
		position_x: 380,
		position_y: 280,
	},
	{
		id: '2',
		clusterId: '1',
		title: 'What is Cyber Crime',
		type: 'article' as const,
		keyword: 'what is cyber crime',
		volume: 1200,
		kd: 18,
		funnel: 'tofu' as const,
		status: 'published' as const,
		seoScore: 91,
		croScore: 0,
		wordCount: 1100,
		targetWordCount: 1050,
		position_x: 100,
		position_y: 80,
	},
	{
		id: '3',
		clusterId: '1',
		title: 'How to Prevent Cyber Crime',
		type: 'article' as const,
		keyword: 'how to prevent cyber crime',
		volume: 890,
		kd: 12,
		funnel: 'tofu' as const,
		status: 'draft' as const,
		seoScore: 72,
		croScore: 0,
		wordCount: 680,
		targetWordCount: 980,
		position_x: 280,
		position_y: 60,
	},
	{
		id: '4',
		clusterId: '1',
		title: 'Is Cyberbullying a Crime',
		type: 'article' as const,
		keyword: 'is cyberbullying a crime',
		volume: 640,
		kd: 9,
		funnel: 'tofu' as const,
		status: 'notStarted' as const,
		seoScore: 0,
		croScore: 0,
		wordCount: 0,
		targetWordCount: 900,
		position_x: 480,
		position_y: 60,
	},
	{
		id: '5',
		clusterId: '1',
		title: 'Can a PI Investigate Cyber Crime',
		type: 'article' as const,
		keyword: 'private investigator cyber crime',
		volume: 480,
		kd: 22,
		funnel: 'mofu' as const,
		status: 'notStarted' as const,
		seoScore: 0,
		croScore: 0,
		wordCount: 0,
		targetWordCount: 1100,
		position_x: 660,
		position_y: 80,
	},
	{
		id: '6',
		clusterId: '1',
		title: 'What is Online Fraud',
		type: 'article' as const,
		keyword: 'what is online fraud',
		volume: 720,
		kd: 14,
		funnel: 'tofu' as const,
		status: 'notStarted' as const,
		seoScore: 0,
		croScore: 0,
		wordCount: 0,
		targetWordCount: 850,
		position_x: 80,
		position_y: 320,
	},
	{
		id: '7',
		clusterId: '1',
		title: 'How to Report Cybercrime',
		type: 'article' as const,
		keyword: 'how to report cybercrime',
		volume: 390,
		kd: 19,
		funnel: 'mofu' as const,
		status: 'notStarted' as const,
		seoScore: 0,
		croScore: 0,
		wordCount: 0,
		targetWordCount: 1000,
		position_x: 680,
		position_y: 300,
	},
	{
		id: '8',
		clusterId: '1',
		title: 'Cyber Crime Investigation Cost',
		type: 'article' as const,
		keyword: 'cyber crime investigation cost',
		volume: 310,
		kd: 26,
		funnel: 'bofu' as const,
		status: 'notStarted' as const,
		seoScore: 0,
		croScore: 0,
		wordCount: 0,
		targetWordCount: 950,
		position_x: 140,
		position_y: 490,
	},
	{
		id: '9',
		clusterId: '1',
		title: 'Hire a Cyber Crime Investigator',
		type: 'article' as const,
		keyword: 'hire cyber crime investigator',
		volume: 210,
		kd: 31,
		funnel: 'bofu' as const,
		status: 'notStarted' as const,
		seoScore: 0,
		croScore: 0,
		wordCount: 0,
		targetWordCount: 900,
		position_x: 600,
		position_y: 490,
	},
	{
		id: '10',
		clusterId: '1',
		title: 'Cyber Stalking Investigation',
		type: 'article' as const,
		keyword: 'cyberstalking investigation',
		volume: 580,
		kd: 16,
		funnel: 'tofu' as const,
		status: 'notStarted' as const,
		seoScore: 0,
		croScore: 0,
		wordCount: 0,
		targetWordCount: 1050,
		position_x: 360,
		position_y: 510,
	},
];

export const mockPerformance = {
	impressions: 42100,
	impressionsDelta: 34,
	clicks: 1840,
	clicksDelta: 28,
	ctr: 4.4,
	ctrDelta: -0.5,
	avgPosition: 18.4,
	positionDelta: 4.7,
	keywords: [
		{ keyword: 'cyber crime investigation', position: 14, change: 4, impressions: 8200, ctr: 2.1, pageId: '1' },
		{ keyword: 'what is cyber crime', position: 6, change: 11, impressions: 3400, ctr: 6.8, pageId: '2' },
		{ keyword: 'private investigator cyber crime', position: 22, change: 3, impressions: 1100, ctr: 1.4, pageId: '5' },
		{ keyword: 'how to report cybercrime', position: 31, change: 0, impressions: 890, ctr: 0.9, pageId: '7' },
		{ keyword: 'cyberstalking private investigator', position: 8, change: -2, impressions: 620, ctr: 5.2, pageId: '10' },
	],
	trafficData: [
		{ month: 'Sep', clicks: 420 },
		{ month: 'Oct', clicks: 680 },
		{ month: 'Nov', clicks: 890 },
		{ month: 'Dec', clicks: 1040 },
		{ month: 'Jan', clicks: 1380 },
		{ month: 'Feb', clicks: 1840 },
	],
};
