import { Lead } from './contexts/DataContext';

export const mockLeads: Lead[] = [
	{
        id: '1',
        name: 'Aiden Smith',
        email: 'asmith@techcompany.com',
        phone: '123-456-7890',
        company: 'TechFlow Solutions',
        stage: 'new',
        value: 50000,
        title: 'Lead: Aiden Smith - TechFlow Solutions',
        description: 'New lead from TechFlow Solutions interested in our AI sales automation platform',
        category: 'SaaS',
        status: 'active',
        priority: 'medium',
        tags: ['new-lead', 'saas', 'qualified'],
        assignedTo: [
            {
                id: '12345',
                role: 'admin',
                organizationId: '12345',
                profile: {
                    id: '12345',
                    first_name: 'John',
                    last_name: 'Doe',
                    avatar: 'https://i.pravatar.cc/150?u=john.doe',
                    completed_onboarding: true
                }
            }
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
    },
	{
        id: '2',
        name: 'Jackson Walker',
        email: 'jwalker@innovatecorp.com',
        phone: '123-456-7890',
        company: 'InnovateCorp',
        stage: 'qualified',
        value: 75000,
        title: 'Lead: Jackson Walker - InnovateCorp',
        description: 'Qualified lead from InnovateCorp looking for enterprise sales automation solution',
        category: 'Enterprise',
        status: 'active',
        priority: 'high',
        tags: ['qualified', 'enterprise', 'high-value'],
        assignedTo: [],
        createdAt: new Date(),
        updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
    },
	{
		id: '3',
        name: 'Sophia Smith',
        email: 'ssmith@growthdynamics.com',
        phone: '123-456-7890',
        company: 'Growth Dynamics',
        stage: 'proposal',
        value: 100000,
		title: 'Lead: Sophia Smith - Growth Dynamics',
		description: 'Proposal stage lead from Growth Dynamics, ready for final presentation',
		category: 'Consulting',
		status: 'active',
		priority: 'critical',
		tags: ['proposal', 'consulting', 'closing'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '4',
        name: 'Jackson Garcia',
        email: 'jgarcia@startupinc.com',
        phone: '123-456-7890',
        company: 'Startup Inc.',
        stage: 'new',
        value: 25000,
		title: 'Lead: Jackson Garcia - Startup Inc.',
		description: 'New startup lead interested in our CRM solution for small teams',
		category: 'Startup',
		status: 'active',
		priority: 'low',
		tags: ['startup', 'small-team', 'new-lead'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '5',
        name: 'Sophia Walker',
        email: 'swalker@enterpriseco.com',
        phone: '123-456-7890',
        company: 'Enterprise Co.',
        stage: 'contacted',
        value: 150000,
		title: 'Lead: Sophia Walker - Enterprise Co.',
		description: 'Discovery call scheduled with Enterprise Co. for large-scale implementation',
		category: 'Enterprise',
		status: 'active',
		priority: 'high',
		tags: ['enterprise', 'discovery', 'high-value'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '6',
        name: 'Olivia Rodriguez',
        email: 'orodriguez@techstartup.com',
        phone: '123-456-7890',
        company: 'Tech Startup',
        stage: 'qualified',
        value: 60000,
		title: 'Lead: Olivia Rodriguez - Tech Startup',
		description: 'Qualified lead from Tech Startup interested in AI sales assistant features',
		category: 'SaaS',
		status: 'active',
		priority: 'medium',
		tags: ['qualified', 'saas', 'ai-features'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '7',
        name: 'Olivia Walker',
        email: 'owalker@consultingfirm.com',
        phone: '123-456-7890',
        		company: 'Consulting Firm',
        stage: 'closed-won',
        value: 80000,
		    title: 'Lead: Olivia Walker - Consulting Firm',
		description: 'Closed deal with Consulting Firm for sales automation implementation',
		category: 'Consulting',
		status: 'closed',
		priority: 'high',
		tags: ['closed', 'consulting', 'won'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '8',
        name: 'Olivia Johnson',
        email: 'ojohnson@midmarket.com',
        phone: '123-456-7890',
        		company: 'Mid-Market Solutions',
        stage: 'proposal',
        value: 90000,
		title: 'Lead: Olivia Johnson - Mid-Market Solutions',
		description: 'Negotiation stage with Mid-Market Solutions for CRM implementation',
		category: 'Mid-Market',
		status: 'active',
		priority: 'high',
		tags: ['negotiation', 'mid-market', 'closing'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '9',
        name: 'Lucas Rodriguez',
        email: 'lrodriguez@enterprisegroup.com',
        phone: '123-456-7890',
        		company: 'Enterprise Group',
        stage: 'closed-won',
        value: 200000,
		title: 'Lead: Lucas Rodriguez - Enterprise Group',
		description: 'Closed enterprise deal with Enterprise Group for multi-department CRM rollout',
		category: 'Enterprise',
		status: 'closed',
		priority: 'critical',
		tags: ['closed', 'enterprise', 'won', 'large-deal'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '10',
        name: 'Lucas Walker',
        email: 'lwalker@smallbusiness.com',
        phone: '123-456-7890',
        company: 'Small Business Co.',
        stage: 'new',
        value: 15000,
		title: 'Lead: Lucas Walker - Small Business Co.',
		description: 'New lead from Small Business Co. interested in basic CRM features',
		category: 'Small Business',
		status: 'active',
		priority: 'low',
		tags: ['new-lead', 'small-business', 'basic-features'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	}
];
