import { Lead } from './contexts/DataContext';

export const mockLeads: Lead[] = [
	{
        id: '1',
        name: 'Aiden Smith',
        email: 'asmith@example.com',
        phone: '123-456-7890',
        company: 'Acme Inc.',
        stage: 'new',
        value: 100000,
        title: 'Case involving Aiden Smith',
        description: 'Investigate activity linked to Aiden Smith (asmith@example.com)',
        category: 'Cyber Security',
        status: 'active',
        priority: 'low',
        tags: ['osint', 'investigation', 'first'],
        assignedTo: [
            {
                id: '12345',
                role: 'admin',
                organizationId: '12345',
                profile: {
                    id: '12345',
                    first_name: 'John',
                    last_name: 'Doe',
                    avatar: 'https://i.pravatar.cc/150?u=john.doe',
                    completed_onboarding: true
                }
            }
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
    },
	{
        id: '2',
        name: 'Jackson Walker',
        email: 'jwalker@example.com',
        phone: '123-456-7890',
        company: 'Acme Inc.',
        stage: 'new',
        value: 100000,
        title: 'Case involving Jackson Walker',
        description: 'Investigate activity linked to Jackson Walker (jwalker@example.com)',
        category: 'Cyber Security',
        status: 'closed',
        priority: 'high',
        tags: ['osint', 'investigation'],
        assignedTo: [],
        createdAt: new Date(),
        updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
    },
	{
		id: '3',
        name: 'Sophia Smith',
        email: 'ssmith@example.com',
        phone: '123-456-7890',
        company: 'Acme Inc.',
        stage: 'new',
        value: 100000,
		title: 'Case involving Sophia Smith',
		description: 'Investigate activity linked to Sophia Smith (ssmith@example.com)',
		category: 'Cyber Security',
		status: 'active',
		priority: 'critical',
		tags: ['osint', 'investigation'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '4',
        name: 'Jackson Garcia',
        email: 'jgarcia@example.com',
        phone: '123-456-7890',
        company: 'Acme Inc.',
        stage: 'new',
        value: 100000,
		title: 'Case involving Jackson Garcia',
		description: 'Investigate activity linked to Jackson Garcia (jgarcia@example.com)',
		category: 'Cyber Security',
		status: 'in_progress',
		priority: 'low',
		tags: ['osint', 'investigation'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '5',
        name: 'Sophia Walker',
        email: 'swalker@example.com',
        phone: '123-456-7890',
        company: 'Acme Inc.',
        stage: 'new',
        value: 100000,
		title: 'Case involving Sophia Walker',
		description: 'Investigate activity linked to Sophia Walker (swalker@example.com)',
		category: 'Cyber Security',
		status: 'in_progress',
		priority: 'low',
		tags: ['osint', 'investigation'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '6',
        name: 'Olivia Rodriguez',
        email: 'orodriguez@example.com',
        phone: '123-456-7890',
        company: 'Acme Inc.',
        stage: 'new',
        value: 100000,
		title: 'Case involving Olivia Rodriguez',
		description: 'Investigate activity linked to Olivia Rodriguez (orodriguez@example.com)',
		category: 'Cyber Security',
		status: 'active',
		priority: 'high',
		tags: ['osint', 'investigation'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '7',
        name: 'Olivia Walker',
        email: 'owalker@example.com',
        phone: '123-456-7890',
        company: 'Acme Inc.',
        stage: 'new',
        value: 100000,
		    title: 'Case involving Olivia Walker',
		description: 'Investigate activity linked to Olivia Walker (owalker@example.com)',
		category: 'Cyber Security',
		status: 'closed',
		priority: 'high',
		tags: ['osint', 'investigation'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '8',
        name: 'Olivia Johnson',
        email: 'ojohnson@example.com',
        phone: '123-456-7890',
        company: 'Acme Inc.',
        stage: 'new',
        value: 100000,
		title: 'Case involving Olivia Johnson',
		description: 'Investigate activity linked to Olivia Johnson (ojohnson@example.com)',
		category: 'Cyber Security',
		status: 'active',
		priority: 'high',
		tags: ['osint', 'investigation'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '9',
        name: 'Lucas Rodriguez',
        email: 'lrodriguez@example.com',
        phone: '123-456-7890',
        company: 'Acme Inc.',
        stage: 'new',
        value: 100000,
		title: 'Case involving Lucas Rodriguez',
		description: 'Investigate activity linked to Lucas Rodriguez (lrodriguez@example.com)',
		category: 'Cyber Security',
		status: 'closed',
		priority: 'critical',
		tags: ['osint', 'investigation'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	},
	{
		id: '10',
        name: 'Olivia Johnson',
        email: 'ojohnson@example.com',
        phone: '123-456-7890',
        company: 'Acme Inc.',
        stage: 'new',
        value: 100000,
		title: 'Case involving Olivia Johnson',
		description: 'Investigate activity linked to Olivia Johnson (ojohnson@example.com)',
		category: 'Cyber Security',
		status: 'in_progress',
		priority: 'high',
		tags: ['osint', 'investigation'],
		assignedTo: [],
		createdAt: new Date(),
		updatedAt: new Date(),
        lastContact: '',
        notes: '',
        communications: []
	}
];
